### ISSUE TITLE
Reorder CONTRIBUTING.md

### ISSUE THREAD

**Issue by srini047** [nerdynikhil/codestreak#15]
<img width="617" alt="Screenshot 2022-12-14 at 1 47 12 AM" src="https://user-images.githubusercontent.com/81156510/207435058-d3ac0c67-8872-4e79-9e6f-b1f92a36ce4d.png">

Change the order of the 2nd and 3rd steps.

**Comment by nerdynikhil** [comment]
Thanks @srini047 for bringing it up. Please go ahead and fix it.
