### ISSUE TITLE
Resolve dependencies

### ISSUE THREAD

**Issue by nerdynikhil** [nerdynikhil/codestreak#3]

**Comment by SattyamSamania** [comment]
Hey @nerdynikhil can you please explain what to do in this issue so that I can take and start working.

**Comment by SattyamSamania** [comment]
> Hey @SattyamSamania. Firstly, thanks for willing to contribute to Codestreak. This looks like a really old issue. It's been fixed. You can take a look on the project by setting it up locally, open up your own issues and then work on them.
> 
> Cheers

Sure. Thanks for the reply.
