### ISSUE TITLE
Feature: Our contributors to README.md

### ISSUE THREAD

**Issue by rushikeshadhav** [nerdynikhil/codestreak#6]
We can add our contributors section to README . 
It will motivate new contributors to contribute to this project.

**Comment by nerdynikhil** [comment]
Cool idea! @rushikeshadhav. I'm assigning it to you.

**Comment by nerdynikhil** [comment]
Hey @SattyamSamania. I'm sorry, but I see that this issue was supposed to be closed. You can pick up other issues or even create a new one if you want to suggest anything and work on it.
